### ISSUE TITLE
Possible Broken

### ISSUE THREAD

**Issue by naxIO** [CodeRect/voxel-warriors#2]
Hi, 

awesome project but I'm having big troubles with it. It seems the interface is broken and one is unable to play. Any ideas?

Cheers

**Comment by CodeRect** [comment]
i have not heard of any issues with it yet. could you explain it in more detail? what is wrong with it? could you provide a screenshot?

**Comment by CodeRect** [comment]
since there is no response, i will assume that this has eventually not been an issue.
